-- MySQL Script generated by MySQL Workbench
-- Thu Jul 10 17:55:08 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Author` (
  `idAuthor` INT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `MiddleName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `DateOfBirth` DATE NULL,
  `DateOfDeath` DATE NULL,
  `BriefInformation` TEXT(300) NULL,
  PRIMARY KEY (`idAuthor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BookCondition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BookCondition` (
  `idBookCondition` INT NULL AUTO_INCREMENT,
  `Condition` VARCHAR(20) NOT NULL,
  `Description` VARCHAR(300) NULL,
  PRIMARY KEY (`idBookCondition`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BookStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BookStatus` (
  `idBookStatus` INT NULL AUTO_INCREMENT,
  `BookStatus` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idBookStatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`JobTitle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`JobTitle` (
  `idJobTitle` INT NULL AUTO_INCREMENT,
  `JobTitle` VARCHAR(45) NOT NULL,
  `Responsibilities` VARCHAR(300) NULL,
  PRIMARY KEY (`idJobTitle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `idEmployee` INT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `MiddleName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(45) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  `HiringDate` DATE NOT NULL,
  `JobTitle_idJobTitle` INT NOT NULL,
  PRIMARY KEY (`idEmployee`, `JobTitle_idJobTitle`),
  INDEX `fk_Employee_JobTitle1_idx` (`JobTitle_idJobTitle` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_JobTitle1`
    FOREIGN KEY (`JobTitle_idJobTitle`)
    REFERENCES `mydb`.`JobTitle` (`idJobTitle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `idBuyer` INT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `MiddleName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(45) NULL,
  `PostalAddress` VARCHAR(45) NULL,
  PRIMARY KEY (`idBuyer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrderStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OrderStatus` (
  `idOrderStatus` INT NULL AUTO_INCREMENT,
  `OrderStatus` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOrderStatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PaymentMethod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PaymentMethod` (
  `idPaymentMethod` INT NULL AUTO_INCREMENT,
  `PaymentMethodcol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPaymentMethod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `idOrder` INT NULL AUTO_INCREMENT,
  `OrderDate` DATE NOT NULL,
  `DeliveryDate` DATE NOT NULL,
  `OrderStatus_idOrderStatus` INT NOT NULL,
  `PaymentMethod_idPaymentMethod` INT NOT NULL,
  `Customer_idBuyer` INT NOT NULL,
  `Employee_idEmployee` INT NOT NULL,
  `Employee_JobTitle_idJobTitle` INT NOT NULL,
  PRIMARY KEY (`idOrder`, `OrderStatus_idOrderStatus`, `PaymentMethod_idPaymentMethod`, `Customer_idBuyer`, `Employee_idEmployee`, `Employee_JobTitle_idJobTitle`),
  INDEX `fk_Order_OrderStatus1_idx` (`OrderStatus_idOrderStatus` ASC) VISIBLE,
  INDEX `fk_Order_PaymentMethod1_idx` (`PaymentMethod_idPaymentMethod` ASC) VISIBLE,
  INDEX `fk_Order_Customer1_idx` (`Customer_idBuyer` ASC) VISIBLE,
  INDEX `fk_Order_Employee1_idx` (`Employee_idEmployee` ASC, `Employee_JobTitle_idJobTitle` ASC) VISIBLE,
  CONSTRAINT `fk_Order_OrderStatus1`
    FOREIGN KEY (`OrderStatus_idOrderStatus`)
    REFERENCES `mydb`.`OrderStatus` (`idOrderStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_PaymentMethod1`
    FOREIGN KEY (`PaymentMethod_idPaymentMethod`)
    REFERENCES `mydb`.`PaymentMethod` (`idPaymentMethod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Customer1`
    FOREIGN KEY (`Customer_idBuyer`)
    REFERENCES `mydb`.`Customer` (`idBuyer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Employee1`
    FOREIGN KEY (`Employee_idEmployee` , `Employee_JobTitle_idJobTitle`)
    REFERENCES `mydb`.`Employee` (`idEmployee` , `JobTitle_idJobTitle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Book` (
  `idBook` INT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NOT NULL,
  `PublishingHouse` VARCHAR(45) NULL,
  `PublicationDate` DATE NULL,
  `RevisionNumber` VARCHAR(45) NULL,
  PRIMARY KEY (`idBook`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BookExample`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BookExample` (
  `idBookExample` INT NULL AUTO_INCREMENT,
  `Cost` DECIMAL(10,2) NOT NULL,
  `Price` DECIMAL(10,2) NOT NULL,
  `Book_idBook` INT NOT NULL,
  `BookCondition_idBookCondition` INT NOT NULL,
  `BookStatus_idBookStatus` INT NOT NULL,
  `Order_idOrder` INT NOT NULL,
  `Order_OrderStatus_idOrderStatus` INT NOT NULL,
  `Order_PaymentMethod_idPaymentMethod` INT NOT NULL,
  `Order_Customer_idBuyer` INT NOT NULL,
  `Order_Employee_idEmployee` INT NOT NULL,
  `Order_Employee_JobTitle_idJobTitle` INT NOT NULL,
  PRIMARY KEY (`idBookExample`, `Book_idBook`, `BookCondition_idBookCondition`, `BookStatus_idBookStatus`, `Order_idOrder`, `Order_OrderStatus_idOrderStatus`, `Order_PaymentMethod_idPaymentMethod`, `Order_Customer_idBuyer`, `Order_Employee_idEmployee`, `Order_Employee_JobTitle_idJobTitle`),
  INDEX `fk_BookExample_Book1_idx` (`Book_idBook` ASC) VISIBLE,
  INDEX `fk_BookExample_BookCondition1_idx` (`BookCondition_idBookCondition` ASC) VISIBLE,
  INDEX `fk_BookExample_BookStatus1_idx` (`BookStatus_idBookStatus` ASC) VISIBLE,
  INDEX `fk_BookExample_Order1_idx` (`Order_idOrder` ASC, `Order_OrderStatus_idOrderStatus` ASC, `Order_PaymentMethod_idPaymentMethod` ASC, `Order_Customer_idBuyer` ASC, `Order_Employee_idEmployee` ASC, `Order_Employee_JobTitle_idJobTitle` ASC) VISIBLE,
  CONSTRAINT `fk_BookExample_Book1`
    FOREIGN KEY (`Book_idBook`)
    REFERENCES `mydb`.`Book` (`idBook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BookExample_BookCondition1`
    FOREIGN KEY (`BookCondition_idBookCondition`)
    REFERENCES `mydb`.`BookCondition` (`idBookCondition`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BookExample_BookStatus1`
    FOREIGN KEY (`BookStatus_idBookStatus`)
    REFERENCES `mydb`.`BookStatus` (`idBookStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BookExample_Order1`
    FOREIGN KEY (`Order_idOrder` , `Order_OrderStatus_idOrderStatus` , `Order_PaymentMethod_idPaymentMethod` , `Order_Customer_idBuyer` , `Order_Employee_idEmployee` , `Order_Employee_JobTitle_idJobTitle`)
    REFERENCES `mydb`.`Order` (`idOrder` , `OrderStatus_idOrderStatus` , `PaymentMethod_idPaymentMethod` , `Customer_idBuyer` , `Employee_idEmployee` , `Employee_JobTitle_idJobTitle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Author_has_Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Author_has_Book` (
  `Author_idAuthor` INT NOT NULL,
  `Book_idBook` INT NOT NULL,
  PRIMARY KEY (`Author_idAuthor`, `Book_idBook`),
  INDEX `fk_Author_has_Book_Book1_idx` (`Book_idBook` ASC) VISIBLE,
  INDEX `fk_Author_has_Book_Author_idx` (`Author_idAuthor` ASC) VISIBLE,
  CONSTRAINT `fk_Author_has_Book_Author`
    FOREIGN KEY (`Author_idAuthor`)
    REFERENCES `mydb`.`Author` (`idAuthor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Author_has_Book_Book1`
    FOREIGN KEY (`Book_idBook`)
    REFERENCES `mydb`.`Book` (`idBook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
